steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - southamerica-west1-docker.pkg.dev/tesis-experiment/tcommerce-repo/tcommerce-api:v1
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - southamerica-west1-docker.pkg.dev/tesis-experiment/tcommerce-repo/tcommerce-api:v1

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - tcommerce-api
      - --image=southamerica-west1-docker.pkg.dev/tesis-experiment/tcommerce-repo/tcommerce-api:v1
      - --region=southamerica-west1
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=cloud-run-tcommerce@tesis-experiment.iam.gserviceaccount.com
      - --set-env-vars=DB_URL=jdbc:postgresql://ep-young-fog-acicnie2-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require,DB_USERNAME=neondb_owner,SERVER_DOMAIN=https://t-commerce.com,SPRING_LOG_LEVEL=DEBUG,HIBERNATE_LOG_LEVEL=ERROR,GCP_PROJECT_ID=tesis-experiment,JWT_EXPIRATION=900000,JWT_COOKIE_NAME=jwt-cookie,JWT_REFRESH_EXPIRATION=1296000000,JWT_REFRESH_COOKIE_NAME=refresh-jwt-cookie,GCS_BUCKET_NAME=t-commerce_storage,GCS_SUBDIRECTORY=products_images,EMAIL_MOCK_ENABLED=false,EMAIL_SMTP_ENABLED=true,EMAIL_SMTP_FROM=test@test.com,SMTP_HOST=sandbox.smtp.mailtrap.io,SMTP_PORT=2525,SMTP_TLS=yes,EMAIL_REST_ENABLED=false,EMAIL_REST_RESEND_ENABLED=true,GRAPHIQL_ENABLED=true
      - --set-secrets=DB_PASSWORD=DB_PASSWORD:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,EMAIL_REST_RESEND_API_KEY=EMAIL_REST_RESEND_API_KEY:latest,EMAIL_REST_RESEND_FROM=EMAIL_REST_RESEND_FROM:latest,EMAIL_REST_SENDGRID_API_KEY=EMAIL_REST_SENDGRID_API_KEY:latest,EMAIL_REST_SENDGRID_FROM=EMAIL_REST_SENDGRID_FROM:latest,SMTP_USERNAME=SMTP_USERNAME:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest

images:
  - southamerica-west1-docker.pkg.dev/tesis-experiment/tcommerce-repo/tcommerce-api:v1

options:
  logging: CLOUD_LOGGING_ONLY