spring.application.name=TCommerce

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=<YOUR_URL>
spring.datasource.username=<YOUR_USERNAME>
spring.datasource.password=<YOUR_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=ERROR

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

spring.cloud.gcp.project-id=<YOUR_PROJECT_ID>
spring.cloud.gcp.credentials.location=file:src/main/resources/credentials/<SERVICE_ACCOUNT_NAME>.json

application.security.jwt.secret-key=<YOUR_SECRET_KEY>
application.security.jwt.expiration=<YOUR_EXPIRATION>
application.security.jwt.refresh-token.expiration=<YOUR_REFRESH_TOKEN_EXPIRATION>
application.security.jwt.cookie-name=<YOUR_COOKIE_NAME>

gcs.bucket-name=<YOUR_BUCKET_NAME>
gcs.subdirectory=<YOUR_SUBDIRECTORY>