spring.application.name=TCommerce

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=<YOUR_DB_URL>
spring.datasource.username=<YOUR_DB_USERNAME>
spring.datasource.password=<YOUR_DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.domain=http://localhost:8080

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=ERROR

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

spring.cloud.gcp.project-id=<YOUR_GCP_PROJECT_ID>
spring.cloud.gcp.credentials.location=<YOUR_GCP_CREDENTIALS_LOCATION>

application.security.jwt.secret-key=<YOUR_JWT_SECRET_KEY>
application.security.jwt.expiration=<YOUR_JWT_EXPIRATION>
application.security.jwt.cookie-name=<YOUR_JWT_COOKIE_NAME>
application.security.jwt.refresh-token.expiration=1296000000
application.security.jwt.refresh-token.cookie-name=refresh-jwt-cookie

gcs.bucket-name=<YOUR_GCS_BUCKET_NAME>
gcs.subdirectory=<YOUR_GCS_BUCKET_SUBDIRECTORY>

# Email Mock Variables
email.mock.enabled=false

# Email SMTP Variables
email.smtp.enabled=false
email.smtp.from=<YOUR_EMAIL_SMTP_FROM>

spring.mail.host=<YOUR_EMAIL_SMTP_HOST>
spring.mail.port=<YOUR_EMAIL_SMTP_PORT>
spring.mail.tls=<YOUR_EMAIL_SMTP_TLS>
spring.mail.username=<YOUR_EMAIL_SMTP_USERNAME>
spring.mail.password=<YOUR_EMAIL_SMTP_PASSWORD>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email API Sendgrid Variable
email.rest.sendgrid.enabled=false
email.rest.sendgrid.api-key=<YOUR_EMAIL_REST_SENDGRID_API_KEY>
email.rest.sendgrid.from=<YOUR_EMAIL_REST_SENDGRID_FROM>

email.rest.resend.enabled=true
email.rest.resend.api-key=re_TKtZAnY8_6i2UScytX4PNb47sPRa2oC7X
email.rest.resend.from=no-reply@ingenieriasoluciones.com.pe

# Stripe Configuration
stripe.secret-key=<YOUR_STRIPE_SECRET_KEY>
stripe.webhook-secret=<YOUR_STRIPE_WEBHOOK_SECRET>

# GraphQL Configuration
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiqlspring.cloud.gcp.sql.enabled=false

spring.cloud.gcp.sql.enabled=false
