spring.application.name=TCommerce

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==========================
# DATABASE
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# SERVER
# ==========================
server.port=${PORT:8080}
server.domain=${SERVER_DOMAIN:http://localhost:8080}

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework=${SPRING_LOG_LEVEL:INFO}
logging.level.org.hibernate=${HIBERNATE_LOG_LEVEL:ERROR}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# ==========================
# GCP
# ==========================
spring.cloud.gcp.project-id=${GCP_PROJECT_ID}

# ==========================
# JWT
# ==========================
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.cookie-name=${JWT_COOKIE_NAME}
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}
application.security.jwt.refresh-token.cookie-name=${JWT_REFRESH_COOKIE_NAME}

# ==========================
# GOOGLE CLOUD STORAGE
# ==========================
gcs.bucket-name=${GCS_BUCKET_NAME}
gcs.subdirectory=${GCS_SUBDIRECTORY}

# ==========================
# EMAIL
# ==========================
email.mock.enabled=${EMAIL_MOCK_ENABLED:true}

email.smtp.enabled=${EMAIL_SMTP_ENABLED:false}
email.smtp.from=${EMAIL_SMTP_FROM}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.tls=${SMTP_TLS}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.rest.sendgrid.enabled=${EMAIL_REST_SENDGRID_ENABLED:false}
email.rest.sendgrid.api-key=${EMAIL_REST_SENDGRID_API_KEY}
email.rest.sendgrid.from=${EMAIL_REST_SENDGRID_FROM}

email.rest.resend.enabled=${EMAIL_REST_RESEND_ENABLED:false}
email.rest.resend.api-key=${EMAIL_REST_RESEND_API_KEY}
email.rest.resend.from=${EMAIL_REST_RESEND_FROM}


# ==========================
# STRIPE
# ==========================
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

# ==========================
# GRAPHQL
# ==========================
spring.graphql.graphiql.enabled=${GRAPHIQL_ENABLED:true}
spring.graphql.graphiql.path=/graphiql