
query GetMyOrders($first: Int, $after: String) {
  myOrders(first: $first, after: $after) {
    edges {
      cursor
      node {
        id
        status
        total
        createdAt
        items {
          product {
            id
            name
            price
          }
          quantity
          price
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}

query GetManagerOrders($first: Int, $after: String, $status: OrderStatus) {
  managerOrders(first: $first, after: $after, status: $status) {
    edges {
      cursor
      node {
        id
        userId
        status
        total
        createdAt
        items {
          product {
            name
          }
          quantity
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

mutation AddToCart($productId: ID!, $quantity: Int!) {
  addToCart(productId: $productId, quantity: $quantity) {
    id
    total
    items {
      product {
        id
        name
        price
      }
      quantity
    }
  }
}

mutation RemoveFromCart($productId: ID!) {
  removeFromCart(productId: $productId) {
    id
    total
    items {
      product {
        name
      }
      quantity
    }
  }
}

mutation ClearCart {
  clearCart {
    id
    items {
      product {
        name
      }
    }
    total
  }
}

mutation CreateOrder {
  createOrderFromCart {
    id
    status
    total
    items {
      product {
        name
      }
      quantity
    }
  }
}

mutation UpdateDeliveryStatus($orderId: ID!, $status: OrderStatus!) {
  updateDeliveryStatus(orderId: $orderId, status: $status) {
    id
    status
    updatedAt
  }
}

mutation DisableProduct($productId: ID!) {
  disableProduct(productId: $productId) {
    id
    name
    disabled
  }
}
mutation DeleteProduct($productId: ID!) {
  deleteProduct(productId: $productId)
}

mutation ToggleLike($productId: ID!) {
  toggleLike(productId: $productId)
}
